# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginAppWithFB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loginAppWithFB

    pod 'FBSDKLoginKit'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'

end
